apiVersion: v1
kind: Pod

spec:
  securityContext:
    fsGroup: 1000

  containers:
    - name: ci
      image: jenkins-ci-agent:1.0.0
      imagePullPolicy: IfNotPresent

      resources:
        requests:
          cpu: "500m"
          memory: "768Mi"
        limits:
          cpu: "2"
          memory: "2Gi"

      command:
        - cat

      tty: true

      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

        - name: DOCKER_TLS_CERTDIR
          value: ""

        - name: TRIVY_CACHE_DIR
          value: /cache/trivy

      volumeMounts:
        - name: trivy-cache
          mountPath: /cache/trivy

    - name: dind
      image: docker:28.5.2-dind@sha256:2a232a42256f70d78e3cc5d2b5d6b3276710a0de0596c145f627ecfae90282ac
      imagePullPolicy: IfNotPresent

      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1500m"
          memory: "2Gi"

      securityContext:
        privileged: true

      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""

      args:
        - --host=tcp://0.0.0.0:2375
        - --host=unix:///var/run/docker.sock

      readinessProbe:
        exec:
          command:
            - docker
            - info
        initialDelaySeconds: 3
        periodSeconds: 2
        timeoutSeconds: 2
        failureThreshold: 30

  volumes:
    - name: trivy-cache
      persistentVolumeClaim:
        claimName: trivy-cache
